import { jsonfy } from "~/utils/jsonfy";

const projects = [
  {
    slug: 'markov',
    title: 'Стомотология доктора Маркова',
    stack: ['Nuxt', 'Typescript', 'Scss', 'Vuex', 'GSAP', 'axios'],
    image: 'markov-main.jpg',
    icon: 'grokhotov',
    caption: 'Сайт для стоматологии',
    link: 'https://markov.grokhotov.ru',
    repository: null,
    commerce: true,
    slides: [
      'markov-main.jpg',
      'markov_2.png',
      'markov_3.png',
      'markov_4.png',
      'markov_5.png',
    ],
    description: 'Мы создали этот сайт для стомотологии доктора Маркова. В нём есть несколько красивых эффектов и GSAP анимаций, такие как горизонтальный скролл. Также, там есть интеграция с Яндекс картами. Главная цель проекта - сделать минималистичный и красивый сайт в фирменных цветах.',
    designed: 'командой дизайнеров студии Грохотова'
  },
  {
    slug: 'industrial-ts',
    title: 'Industrial technical supply',
    stack: ['Nuxt', 'Javascript', 'Scss', 'Vuex', 'axios'],
    image: 'industrial-ts.jpg',
    icon: 'grokhotov',
    caption: 'Интернет магазин товаров промышленного снабжения. Сейчас находится на первом этапе. Без корзины, но с заявкой на товар.',
    link: 'https://industrial-ts.ru/',
    repository: null,
    commerce: true,
    slides: [
      'industrial-ts.jpg',
      'industrial-ts_2.png',
      'industrial-ts_3.png'
    ],
    description: 'Мы создали этот сайт для российской ретейл компании "Industrial technical supply". В нём были созданы страницы каталогов и одного товара с AOS анимациями. Этот проект был сделан как первый этап интернет-магазина: без корзины, но с формой запроса товара.',
    designed: 'командой дизайнеров студии Грохотова'
  },
  {
    slug: 'grade',
    title: 'Grade',
    stack: ['Vue.js', 'Javascript', 'Scss', 'Vuex', 'GSAP', 'axios'],
    image: 'grade.png',
    icon: 'grokhotov',
    caption: 'Сайт компании "Grade", которая занимается редевелмпентом и реинновацией зданий и помещений.',
    link: 'http://grade.company/',
    repository: null,
    commerce: true,
    slides: [
      'grade.png',
      'grade_2.png',
      'grade_3.png',
      'grade_5.png',
      'grade_4.png',
    ],
    description: 'Этот сайт создан для российской компании по редевелопменту, реинновации и реконструкции зданий "Grade". Он был сделан в креативном дизайне и современном стэке технологий, чтобы показать, что сама компания такой и является.',
    designed: 'командой дизайнеров студии Грохотова'
  },
  {
    slug: 'lpadevice',
    title: 'ЛенСпецАвто',
    stack: ['Vue.js', 'Javascript', 'Scss', 'Vuex', 'axios'],
    image: 'lpa.png',
    icon: 'grokhotov',
    caption: 'Интернет-магазин промышленной электронники',
    link: 'https://lpadevice.ru/',
    repository: null,
    commerce: true,
    slides: [
      'lpa.png',
      'lpa_4.png',
      'lpa_2.png',
      'lpa_3.png',
    ],
    description: 'Этот проект это редизайн старого сайта "ЛенСпецАвто". В нём есть интересный Vue-компонент "Конфигуратор", который полностью динамичный и асинхронный. Он помогает выбрать нужную конфигурацию товара с простым и понятным UI. Корзина сделана классом нативного JS. Этот проект уже помог увеличить прибыль компании.',
    designed: 'командой дизайнеров студии Грохотова'
  },
  {
    slug: 'vue-weather',
    title: 'Vue3 приложение прогноза погоды',
    stack: ['Vue.js', 'Typescript', 'Scss', 'Pinia', 'axios'],
    image: 'vue-weather.png',
    caption: 'Приложение прогноза погоды, написанное на Vue3.',
    link: 'https://vue3-vite-weather-app.vercel.app/',
    repository: 'https://github.com/maxon32/vue3-weather-app',
    commerce: false,
    slides: ['vue-weather.png'],
    description: 'Я сделал этот проект, чтобы проработать основные концепции Pinia и Typescript в Vue3. В нем есть возможность добавить или удалить город и изменять порядок городов. Список сохраняется в localStorage. Для данных я использовал Open Weather Map API.',
    designed: 'мной'
  },
  {
    slug: 'react-weather',
    title: 'React приложение прогноза погоды',
    stack: ['React', 'Typescript', 'Styled components', 'Redux toolkit', 'axios'],
    image: 'react-weather.png',
    caption: 'React weather app with neumorphism design.',
    link: 'https://react-ts-weather-app-openmap.vercel.app/',
    repository: 'https://github.com/eremeev23/react-ts-weather-app',
    commerce: false,
    slides: ['react-weather.png'],
    description: 'Я сделал этот проект, чтобы проработать основные концепции RTK Query и Typescript в React. Также, это тёмная тема такого же проекта на Vue3. В нем есть возможность добавить или удалить город и изменять порядок городов. Список сохраняется в localStorage. Для данных я использовал Open Weather Map API.',
    designed: 'мной'
  },
  {
    slug: 'vue-register',
    title: 'Vue форма входа',
    stack: ['Vue.js', 'Typescript', 'Scss', 'Pinia', 'axios'],
    image: 'vue-register.png',
    caption: 'Форма входа и страница пользователя, написанные на Vue3.',
    link: 'https://eremeev-uprock-test.vercel.app/',
    repository: 'https://github.com/maxon32/uprock-test',
    commerce: false,
    slides: ['vue-register.png'],
    description: 'Тестовое задание в компанию "Uprock". Сделана форма входа и страница пользователя с возможностью выйти. При перезагрузке выполнится редирект на страницу пользователя, если он залогирован, либо на форму входа, если нет.',
    designed: 'мной'
  },
  {
    slug: 'users-table',
    title: 'Таблица пользователей',
    stack: ['Vue.js', 'Javascript', 'Scss', 'Pinia', 'axios'],
    image: 'user-table.png',
    caption: 'Таблица пользователей с поиском и пагинацией, написано на Vue3.',
    link: 'https://users-table-vue.vercel.app/',
    repository: 'https://github.com/maxon32/users-table',
    commerce: false,
    slides: ['user-table.png'],
    description: 'Таблица пользователей с данными из псевдо-api с пагинацией и поиском. Прогресс пагинации и поисковая фраза передаются get-параметрами в адресную строку, что при перезагрузки позволяет сразу получить необходимые данные.',
    designed: 'мной'
  },
  {
    slug: 'react-ecomm',
    title: 'Интернет-магазин одежды',
    stack: ['React', 'Javascript', 'Styled components', 'Redux toolkit'],
    image: 'el-modo.png',
    caption: 'Интернет-магазин одежды, написанный на React.',
    link: 'https://el-modo.vercel.app/',
    repository: 'https://github.com/maxon32/react-rtk-ecommerce',
    commerce: false,
    slides: [
      'el-modo.png',
      'el-modo_2.png',
      'el-modo_3.png',
      'el-modo_4.png',
    ],
    description: 'Интернет-магазин одежды. Я разработал этот проект, чтобы ознакомиться с основными концепциями React и Redux toolkit. В нём есть динамические страницы категорий и товаров. Также, есть возможность добавления товара в корзину.',
    designed: 'мной'
  },
  {
    slug: 'store-gallery',
    title: 'Галлерея интернет-магазина',
    stack: ['Nuxt', 'Javascript', 'CSS', 'Vuex', 'axios'],
    image: 'store-gallery.png',
    caption: 'Галлерея интернет-магазина, написанная на Nuxt. Есть возможность удалять или добавлять товар с сохранением в localStorage.',
    link: 'https://store-gallery.vercel.app/',
    repository: 'https://github.com/maxon32/nuxt-store-gallery',
    commerce: false,
    slides: ['store-gallery.png'],
    description: 'Я делал этот проект, чтобы закрепить свои навыки в Nuxt. В нём можно добавлять свой товар, сортировать список товаров и удалять из него. Список сохраняется в localStorage.',
    designed: 'мной'
  },
  {
    slug: 'react-todo',
    title: 'Todo-лист',
    stack: ['React', 'Typescript', 'Styled components', 'Redux toolkit'],
    image: 'todo.png',
    caption: 'Todo-лист, написанные на React + Redux toolkit',
    link: 'https://store-gallery.vercel.app/',
    repository: 'https://github.com/maxon32/react-ts-todo-list',
    commerce: false,
    slides: ['todo.png'],
    description: 'Простой Todo лист для закрепления навыков в стэке React + Redux toolkit + Typescript.',
    designed: 'мной'
  },
]

export default defineEventHandler(() => jsonfy(projects));
